adaptive-controller-config:
  densification-view-space-position-gradients-threshold: 0.000002
  densification_overlap_tiles_threshold: 16
  gaussian-split-factor-phi: 1.6
  num-iterations-densify: 100
  num-iterations-reset-alpha: 8000
  num-iterations-warm-up: 800
  reset-alpha-value: 0.0
  transparent-alpha-threshold: -2.0
  under-reconstructed-s-threshold: 0.1
  floater_threshold: 3.0
gaussian-point-cloud-scene-config:
  max-num-points-ratio: 100.0
  num-of-features: 56
increase-color-max-sh-band-interval: 1000.0
log-image-interval: 1000
log-loss-interval: 10
log-metrics-interval: 100
enable_taichi_kernel_profiler: True
log_taichi_kernel_profile_interval: 3000
feature_learning_rate: 0.005
position_learning_rate: 0.00005
loss-function-config:
  lambda-value: 0.2
  enable_regularization: False
  regularization_weight: 0.005
num-iterations: 300000
pointcloud-parquet-path: 'data/kitti/point_cloud_downsample.parquet'
rasterisation-config:
  depth-to-sort-key-scale: 10.0
  far-plane: 1000.0
  near-plane: 0.4
summary-writer-log-dir: logs/kitti_experiment_0.01x_points_also_split_large
train-dataset-json-path: 'data/kitti/kitti_train.json'
val-dataset-json-path: 'data/kitti/kitti_val_downsample.json'
val-interval: 5000
